"""add clinic faq entries

Revision ID: 1a1bf9d6815a
Revises: 7c1a54797a80
Create Date: 2026-07-08 20:40:55.397705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1bf9d6815a'
down_revision: Union[str, Sequence[str], None] = '7c1a54797a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_faq_entries',
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.String(length=4000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_faq_entries_clinic_id'), 'clinic_faq_entries', ['clinic_id'], unique=False)
    op.execute(
        "CREATE INDEX ix_clinic_faq_entries_search "
        "ON clinic_faq_entries "
        "USING gin (to_tsvector('simple', question || ' ' || answer))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_clinic_faq_entries_search")
    op.drop_index(op.f('ix_clinic_faq_entries_clinic_id'), table_name='clinic_faq_entries')
    op.drop_table('clinic_faq_entries')
    # ### end Alembic commands ###
